site_name: The Real-Timers Guide to the Computational Galaxy
docs_dir: .
site_dir: ../site
repo_url: https://github.com/absorensen/the-guide

theme:
  language: en
  name: material
  favicon: figures/nebula.png
  logo: figures/nebula.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.indexes
    - content.code.copy
    - navigation.footer
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - glightbox
  - same-dir
  - git-revision-date-localized:
      enable_creation_date: true

extra:
  social:
    - icon: material/email
      link: mailto:aboso@dtu.com
    - icon: fontawesome/brands/github
      link: https://github.com/absorensen
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/anders-bo-sorensen/

nav:
  - Home: README.md
  - Acknowledgements: acknowledgements.md
  - M0 - Introduction:
    - m0_introduction/README.md
    - S0 - Introduction to the Computing Landscape: m0_introduction/s0_intro_to_computing.md
    - S1 - Introduction to Rust: m0_introduction/s1_intro_to_rust.md
    - S2 - Basic Concepts in Rust: m0_introduction/s2_basic_concepts_in_rust.md
    - S3 - 3️⃣ Less Basic Concepts in Rust: m0_introduction/s3_less_basic_concepts_in_rust.md
    - S4 - 4️⃣ Exercises: m0_introduction/s4_exercises.md
  - M1 - Memory Hierarchies:
    - m1_memory_hierarchies/README.md
    - S0 - Soft Memory Hierarchies: m1_memory_hierarchies/s0_soft_memory_hierarchies.md
    - S1 - Computational Graphs: m1_memory_hierarchies/s1_computational_graphs.md
    - S2 - Introduction to GPU's: m1_memory_hierarchies/s2_intro_to_gpus.md
    - S3 - Immediate GPU Computation: m1_memory_hierarchies/s3_immediate_gpu_computation.md
    - S4 - Building a Computational Graph: m1_memory_hierarchies/s4_building_a_computational_graph.md
    - S5 - Computational Graph Compilers: m1_memory_hierarchies/s5_computational_graph_compilers.md
    - S6 - 4️⃣ Exercises: m1_memory_hierarchies/s6_exercises.md    
  - M2 - Parallelism:
    - m2_parallelism/README.md
    - S0 - Threads: m2_parallelism/s0_threads.md
    - S1 - Data Parallelism: m2_parallelism/s1_data_parallelism.md
    - S2 - Mutex: m2_parallelism/s2_mutex.md
    - S3 - Atomic: m2_parallelism/s3_atomic.md
    - S4 - Message Passing: m2_parallelism/s4_message_passing.md
    - S5 - Async: m2_parallelism/s5_async.md
    - S6 - Events: m2_parallelism/s6_events.md
    - S7 - 3️⃣ More GPU: m2_parallelism/s7_more_gpu.md
    - S8 - 3️⃣ Branchless Programming: m2_parallelism/s8_branchless_programming.md
    - S9 - 3️⃣ Sparsity: m2_parallelism/s9_sparsity.md
    - S10 - 3️⃣ Sorting and Random Access: m2_parallelism/s10_sorting_and_random_access.md
    - S11 - 3️⃣ Parallel Graphs: m2_parallelism/s11_parallel_graphs.md
    - S12 - 4️⃣ Exercises: m2_parallelism/s12_exercises.md
  - M3 - Types:
    - m3_types/README.md
  - M4 - Profilers and Case Studies:
    - m4_profilers/README.md
  - M5 - 3️⃣ Projects:
    - m5_projects/README.md