site_name: The Real-Timers Guide to the Computational Galaxy
docs_dir: .
site_dir: ../site
repo_url: https://github.com/absorensen/the-real-timers-guide-to-the-computational-galaxy

theme:
  language: en
  name: material
  favicon: figures/favicon.png
  logo: figures/mlops_cycle.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.indexes
    - content.code.copy
    - navigation.footer
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - glightbox
  - same-dir
  - git-revision-date-localized:
      enable_creation_date: true

extra:
  social:
    - icon: material/email
      link: mailto:anders-soerensen@hotmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/absorensen
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/anders-bo-sorensen/

nav:
  - Home: README.md
  - Overview: overview.md
  - Acknowledgements: acknowledgements.md
  - M0 - Introduction:
    - m0_introduction/README.md
    - S0 - Introduction to the Computing Landscape: m0_introduction/s0_intro_to_computing.md
    - S1 - Introduction to Rust: m0_introduction/s1_intro_to_rust.md
    - S2 - Basic Concepts in Rust: m0_introduction/s2_basic_concepts_in_rust.md
    - S3 - *Less Basic Concepts in Rust: m0_introduction/s3_less_basic_concepts_in_rust.md
    - S4 - *Exercises: m0_introduction/s4_exercises.md
  - M1 - Memory Hierarchies:
    - m1_memory_hierarchies/README.md
    - S0 - Introduction: m1_memory_hierarchies/s0_intro.md
    - S1 - Memory Hierarchies and the CPU: m1_memory_hierarchies/s1_memory_hierarchies_and_the_cpu.md
    - S2 - Computational Graphs: m1_memory_hierarchies/s2_computational_graphs.md
    - S3 - Introduction To GPU's: m1_memory_hierarchies/s3_intro_to_gpus.md
    - S4 - Immediate GPU Computation: m1_memory_hierarchies/s4_immediate_gpu_computation.md
    - S5 - Building a Computational Graph: m1_memory_hierarchies/s5_building_a_computational_graph.md
    - S6 - Computational Graph Compilers: m1_memory_hierarchies/s6_computational_graph_compilers.md
    - S7 - Outro: m1_memory_hierarchies/s7_outro.md
    - S8 - *Exercises: m1_memory_hierarchies/s8_exercises.md    
  - M2 - Concepts in Parallelism:
    - m2_concepts_in_parallelism/README.md
  - M3 - Types:
    - m3_types/README.md
  - M4 - Profilers and Case Studies:
    - m4_profilers/README.md
  - M5 - *Projects:
    - m5_projects/README.md