site_name: The Real-Timers Guide to the Computational Galaxy
docs_dir: .
site_dir: ../site
repo_url: https://github.com/absorensen/the-real-timers-guide-to-the-computational-galaxy

theme:
  language: en
  name: material
  favicon: figures/favicon.png
  logo: figures/mlops_cycle.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.indexes
    - content.code.copy
    - navigation.footer
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - glightbox
  - same-dir
  - git-revision-date-localized:
      enable_creation_date: true

extra:
  social:
    - icon: material/email
      link: mailto:anders-soerensen@hotmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/absorensen
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/anders-bo-sorensen/

nav:
  - Home: README.md
  - Code: code.md
  - M0 - Introduction:
    - m0_introduction/README.md
  - M1 - Memory Hierarchies:
    - m1_memory_hierarchies/README.md
  - M2 - Concepts in Parallelism:
    - m2_concepts_in_parallelism/README.md
  - M3 - Types:
    - m3_types/README.md
  - M4 - Profilers and Case Studies:
    - m4_profilers/README.md
  - M5 - Projects:
    - m5_projects/README.md